# C
[[language]]
name = "c"
language-servers = ["clangd"]

# C++
[[language]]
name = "cpp"
language-servers = ["clangd"]

# Rust
[[language]]
name = "rust"
language-servers = ["rust-analyzer"]

# Go
[[language]]
name = "go"
language-servers = ["gopls"]


# JavaScript
[[language]]
name = "javascript"
language-servers = ["typescript-language-server"]

# TypeScript
[[language]]
name = "typescript"
language-servers = ["typescript-language-server"]

# Python
[[language]]
name = "python"
language-servers = ["pyright"]
